language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6

script:
    - make libhll.a
    - make php
    - NO_INTERACTION=1 php -n php/run-tests.php -n -d 'extension=php/modules/hll.so' -p `phpenv which php` --show-diff

